
[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0


[keyboard]
bindings = [
{ key = "Enter", mods = "Control|Shift", action = "SpawnNewInstance" },
{key = "Backspace", mods = "Command", chars = "\u001b\u007f"}]

[general]
live_config_reload = true
import = [
  "/home/utsuro/.config/alacritty/theme-generated.toml",
  "/home/utsuro/.config/alacritty/font-generated.toml",
]
