-- Generated by nwg-displays on 2026-05-29 at 17:26:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "0x1080",
    scale = 0.3999999999999998
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
